
name: Mnist_LeNet
seed: 0
n_gpu: 1



arch:
    type: MnistModel
    args:

data_loader:
    type: TextBertDataLoader
    args:
        data_dir: data/birds
        batch_size: 128
        shuffle: True
        validation_split: 0.1
        num_workers: 2

optimizer:
    type: Adam
    args:
        lr: 0.001
        weight_decay: 0
        amsgrad: True

loss: nll_loss
metrics: [my_metric, my_metric2]
lr_scheduler:
    type: StepLR
    args:
        step_size: 50
        gamma: 0.1

trainer:
    epochs: 100
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 10
    tensorboardX: True

# Dataset name: flowers, birds
DATASET_NAME: birds
CONFIG_NAME: ''
DATA_DIR: ''
GPU_ID: 0
CUDA: True
WORKERS: 6

RNN_TYPE: 'LSTM'   # 'GRU'
B_VALIDATION: False

TREE:
    BRANCH_NUM: 3
    BASE_SIZE: 64


# Training options
TRAIN:
    BATCH_SIZE: 64
    MAX_EPOCH: 600
    SNAPSHOT_INTERVAL: 2000
    DISCRIMINATOR_LR: 2e-4
    GENERATOR_LR: 2e-4
    ENCODER_LR: 2e-4
    RNN_GRAD_CLIP: 0.25
    FLAG: True
    NET_E: ''
    NET_G: ''
    B_NET_D: True

    SMOOTH:
        GAMMA1: 5.0
        GAMMA2: 5.0
        GAMMA3: 10.0
        LAMBDA: 1.0


# Model options
GAN:
    DF_DIM: 64
    GF_DIM: 128
    Z_DIM: 100
    CONDITION_DIM: 100
    R_NUM: 2
    B_ATTENTION: True
    B_DCGAN: False

data:
    captions_per_image: 10
    embedding_dim: 256
    words_num: 18
TEXT:
    CAPTIONS_PER_IMAGE: 10
    EMBEDDING_DIM: 256
    WORDS_NUM: 18
